name: Use Reusable PR Workflow

on:
  pull_request:
    types: [opened, synchronize]
    permissions:
      issues: write
      pull-requests: write

jobs:
  call-reusable-workflow:
    uses: ffrizzo/reusable-workflow-test/.github/workflows/pr-file-changes.yml@main
    secrets: inherit
